version: '2'
services:
    cli:
        image: lojassimonetti/php-cli-docker:latest
        volumes:
            - ./:/app
            - ~/.ssh:/root/.ssh
            - ~/.composer:/root/.composer
        env_file:
            - .env
    apache:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
            - ~/.ssh:/root/.ssh
            - ~/.composer:/root/.composer
        ports:
            - 8090:80
    rabbit:
        build:
            context: .
            dockerfile: provisioning/Dockerfile.rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: mestre
        ports:
            - 15673:15672
            - 56723:5672