version: '2'
services:
    cli:
        image: lojassimonetti/php-cli-docker:latest
        volumes:
            - ./:/app
            - ~/.ssh:/root/.ssh
            - ~/.composer:/root/.composer
        env_file:
            - .env
    db:
        image: mysql:5.7
        working_dir: /var/www/html
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        volumes:
            - ./.data/db:/var/lib/mysql
            - ./:/var/www/html
            - /tmp:/tmp
    apache:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
            - ~/.ssh:/root/.ssh
            - ~/.composer:/root/.composer
        working_dir: /var/www/html
        links:
            - db
        ports:
            - 8090:80
    rabbit:
        build:
            context: .
            dockerfile: provisioning/Dockerfile.rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: mestre
        ports:
            - 15673:15672
            - 56723:5672