#!/bin/bash

# Installing dependencies by Composer
echo -e "\nInstalling dependencies...\n"
composer install

# Running Doctrine Migrations
echo -e "\nRunning Doctrine Migrations...\n"
php app/console.php migrations:generate
php app/console.php migrations:migrate